name: cross_connectivity
version: 2.0.1
homepage: https://github.com/marchdev-tk/cross_connectivity
description: A Flutter plugin for handling Connectivity and REAL Connection state in the mobile, web and desktop platforms. Supports iOS, Android, Web, Windows, Linux and macOS.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0
  http: ^0.13.0
  rxdart: ^0.26.0
  connectivity: ^3.0.2
  connectivity_macos: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
